/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiJobsIndexRouteImport } from './routes/api/jobs/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminR2LogsIndexRouteImport } from './routes/admin/r2-logs/index'
import { Route as AdminLlmLogsIndexRouteImport } from './routes/admin/llm-logs/index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminConfigIndexRouteImport } from './routes/admin/config/index'
import { Route as AppExamsIndexRouteImport } from './routes/_app/exams/index'
import { Route as ApiJobsActiveRouteImport } from './routes/api/jobs/active'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppJobsJobIdIndexRouteImport } from './routes/_app/jobs/$jobId/index'
import { Route as AppExamsNewIndexRouteImport } from './routes/_app/exams/new/index'
import { Route as AppExamsExamIdIndexRouteImport } from './routes/_app/exams/$examId/index'
import { Route as ApiJobsIdUploadRouteImport } from './routes/api/jobs/$id/upload'
import { Route as ApiJobsIdStreamRouteImport } from './routes/api/jobs/$id/stream'
import { Route as ApiJobsIdEventsRouteImport } from './routes/api/jobs/$id/events'
import { Route as ApiJobsIdCancelRouteImport } from './routes/api/jobs/$id/cancel'
import { Route as AppExamsExamIdQuizIndexRouteImport } from './routes/_app/exams/$examId/quiz/index'
import { Route as ApiAdminModelsIdTestStreamRouteImport } from './routes/api/admin/models/$id/test-stream'
import { Route as AppExamsExamIdQuizAttemptIdIndexRouteImport } from './routes/_app/exams/$examId/quiz/$attemptId/index'
import { Route as AppExamsExamIdQuizAttemptIdResultRouteImport } from './routes/_app/exams/$examId/quiz/$attemptId/result'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiJobsIndexRoute = ApiJobsIndexRouteImport.update({
  id: '/api/jobs/',
  path: '/api/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminR2LogsIndexRoute = AdminR2LogsIndexRouteImport.update({
  id: '/r2-logs/',
  path: '/r2-logs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLlmLogsIndexRoute = AdminLlmLogsIndexRouteImport.update({
  id: '/llm-logs/',
  path: '/llm-logs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConfigIndexRoute = AdminConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppExamsIndexRoute = AppExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiJobsActiveRoute = ApiJobsActiveRouteImport.update({
  id: '/api/jobs/active',
  path: '/api/jobs/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJobsJobIdIndexRoute = AppJobsJobIdIndexRouteImport.update({
  id: '/jobs/$jobId/',
  path: '/jobs/$jobId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamsNewIndexRoute = AppExamsNewIndexRouteImport.update({
  id: '/exams/new/',
  path: '/exams/new/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamsExamIdIndexRoute = AppExamsExamIdIndexRouteImport.update({
  id: '/exams/$examId/',
  path: '/exams/$examId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiJobsIdUploadRoute = ApiJobsIdUploadRouteImport.update({
  id: '/api/jobs/$id/upload',
  path: '/api/jobs/$id/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdStreamRoute = ApiJobsIdStreamRouteImport.update({
  id: '/api/jobs/$id/stream',
  path: '/api/jobs/$id/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdEventsRoute = ApiJobsIdEventsRouteImport.update({
  id: '/api/jobs/$id/events',
  path: '/api/jobs/$id/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdCancelRoute = ApiJobsIdCancelRouteImport.update({
  id: '/api/jobs/$id/cancel',
  path: '/api/jobs/$id/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExamsExamIdQuizIndexRoute = AppExamsExamIdQuizIndexRouteImport.update({
  id: '/exams/$examId/quiz/',
  path: '/exams/$examId/quiz/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAdminModelsIdTestStreamRoute =
  ApiAdminModelsIdTestStreamRouteImport.update({
    id: '/api/admin/models/$id/test-stream',
    path: '/api/admin/models/$id/test-stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppExamsExamIdQuizAttemptIdIndexRoute =
  AppExamsExamIdQuizAttemptIdIndexRouteImport.update({
    id: '/exams/$examId/quiz/$attemptId/',
    path: '/exams/$examId/quiz/$attemptId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppExamsExamIdQuizAttemptIdResultRoute =
  AppExamsExamIdQuizAttemptIdResultRouteImport.update({
    id: '/exams/$examId/quiz/$attemptId/result',
    path: '/exams/$examId/quiz/$attemptId/result',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/active': typeof ApiJobsActiveRoute
  '/exams/': typeof AppExamsIndexRoute
  '/admin/config/': typeof AdminConfigIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/llm-logs/': typeof AdminLlmLogsIndexRoute
  '/admin/r2-logs/': typeof AdminR2LogsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/jobs/$id/cancel': typeof ApiJobsIdCancelRoute
  '/api/jobs/$id/events': typeof ApiJobsIdEventsRoute
  '/api/jobs/$id/stream': typeof ApiJobsIdStreamRoute
  '/api/jobs/$id/upload': typeof ApiJobsIdUploadRoute
  '/exams/$examId/': typeof AppExamsExamIdIndexRoute
  '/exams/new/': typeof AppExamsNewIndexRoute
  '/jobs/$jobId/': typeof AppJobsJobIdIndexRoute
  '/api/admin/models/$id/test-stream': typeof ApiAdminModelsIdTestStreamRoute
  '/exams/$examId/quiz/': typeof AppExamsExamIdQuizIndexRoute
  '/exams/$examId/quiz/$attemptId/result': typeof AppExamsExamIdQuizAttemptIdResultRoute
  '/exams/$examId/quiz/$attemptId/': typeof AppExamsExamIdQuizAttemptIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/active': typeof ApiJobsActiveRoute
  '/exams': typeof AppExamsIndexRoute
  '/admin/config': typeof AdminConfigIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/llm-logs': typeof AdminLlmLogsIndexRoute
  '/admin/r2-logs': typeof AdminR2LogsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/api/jobs': typeof ApiJobsIndexRoute
  '/api/jobs/$id/cancel': typeof ApiJobsIdCancelRoute
  '/api/jobs/$id/events': typeof ApiJobsIdEventsRoute
  '/api/jobs/$id/stream': typeof ApiJobsIdStreamRoute
  '/api/jobs/$id/upload': typeof ApiJobsIdUploadRoute
  '/exams/$examId': typeof AppExamsExamIdIndexRoute
  '/exams/new': typeof AppExamsNewIndexRoute
  '/jobs/$jobId': typeof AppJobsJobIdIndexRoute
  '/api/admin/models/$id/test-stream': typeof ApiAdminModelsIdTestStreamRoute
  '/exams/$examId/quiz': typeof AppExamsExamIdQuizIndexRoute
  '/exams/$examId/quiz/$attemptId/result': typeof AppExamsExamIdQuizAttemptIdResultRoute
  '/exams/$examId/quiz/$attemptId': typeof AppExamsExamIdQuizAttemptIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/active': typeof ApiJobsActiveRoute
  '/_app/exams/': typeof AppExamsIndexRoute
  '/admin/config/': typeof AdminConfigIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/llm-logs/': typeof AdminLlmLogsIndexRoute
  '/admin/r2-logs/': typeof AdminR2LogsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/jobs/$id/cancel': typeof ApiJobsIdCancelRoute
  '/api/jobs/$id/events': typeof ApiJobsIdEventsRoute
  '/api/jobs/$id/stream': typeof ApiJobsIdStreamRoute
  '/api/jobs/$id/upload': typeof ApiJobsIdUploadRoute
  '/_app/exams/$examId/': typeof AppExamsExamIdIndexRoute
  '/_app/exams/new/': typeof AppExamsNewIndexRoute
  '/_app/jobs/$jobId/': typeof AppJobsJobIdIndexRoute
  '/api/admin/models/$id/test-stream': typeof ApiAdminModelsIdTestStreamRoute
  '/_app/exams/$examId/quiz/': typeof AppExamsExamIdQuizIndexRoute
  '/_app/exams/$examId/quiz/$attemptId/result': typeof AppExamsExamIdQuizAttemptIdResultRoute
  '/_app/exams/$examId/quiz/$attemptId/': typeof AppExamsExamIdQuizAttemptIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/'
    | '/login/'
    | '/api/auth/$'
    | '/api/jobs/active'
    | '/exams/'
    | '/admin/config/'
    | '/admin/jobs/'
    | '/admin/llm-logs/'
    | '/admin/r2-logs/'
    | '/admin/users/'
    | '/api/jobs/'
    | '/api/jobs/$id/cancel'
    | '/api/jobs/$id/events'
    | '/api/jobs/$id/stream'
    | '/api/jobs/$id/upload'
    | '/exams/$examId/'
    | '/exams/new/'
    | '/jobs/$jobId/'
    | '/api/admin/models/$id/test-stream'
    | '/exams/$examId/quiz/'
    | '/exams/$examId/quiz/$attemptId/result'
    | '/exams/$examId/quiz/$attemptId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/api/auth/$'
    | '/api/jobs/active'
    | '/exams'
    | '/admin/config'
    | '/admin/jobs'
    | '/admin/llm-logs'
    | '/admin/r2-logs'
    | '/admin/users'
    | '/api/jobs'
    | '/api/jobs/$id/cancel'
    | '/api/jobs/$id/events'
    | '/api/jobs/$id/stream'
    | '/api/jobs/$id/upload'
    | '/exams/$examId'
    | '/exams/new'
    | '/jobs/$jobId'
    | '/api/admin/models/$id/test-stream'
    | '/exams/$examId/quiz'
    | '/exams/$examId/quiz/$attemptId/result'
    | '/exams/$examId/quiz/$attemptId'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/_app/'
    | '/admin/'
    | '/login/'
    | '/api/auth/$'
    | '/api/jobs/active'
    | '/_app/exams/'
    | '/admin/config/'
    | '/admin/jobs/'
    | '/admin/llm-logs/'
    | '/admin/r2-logs/'
    | '/admin/users/'
    | '/api/jobs/'
    | '/api/jobs/$id/cancel'
    | '/api/jobs/$id/events'
    | '/api/jobs/$id/stream'
    | '/api/jobs/$id/upload'
    | '/_app/exams/$examId/'
    | '/_app/exams/new/'
    | '/_app/jobs/$jobId/'
    | '/api/admin/models/$id/test-stream'
    | '/_app/exams/$examId/quiz/'
    | '/_app/exams/$examId/quiz/$attemptId/result'
    | '/_app/exams/$examId/quiz/$attemptId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiJobsActiveRoute: typeof ApiJobsActiveRoute
  ApiJobsIndexRoute: typeof ApiJobsIndexRoute
  ApiJobsIdCancelRoute: typeof ApiJobsIdCancelRoute
  ApiJobsIdEventsRoute: typeof ApiJobsIdEventsRoute
  ApiJobsIdStreamRoute: typeof ApiJobsIdStreamRoute
  ApiJobsIdUploadRoute: typeof ApiJobsIdUploadRoute
  ApiAdminModelsIdTestStreamRoute: typeof ApiAdminModelsIdTestStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/jobs/': {
      id: '/api/jobs/'
      path: '/api/jobs'
      fullPath: '/api/jobs/'
      preLoaderRoute: typeof ApiJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/r2-logs/': {
      id: '/admin/r2-logs/'
      path: '/r2-logs'
      fullPath: '/admin/r2-logs/'
      preLoaderRoute: typeof AdminR2LogsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/llm-logs/': {
      id: '/admin/llm-logs/'
      path: '/llm-logs'
      fullPath: '/admin/llm-logs/'
      preLoaderRoute: typeof AdminLlmLogsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/config/': {
      id: '/admin/config/'
      path: '/config'
      fullPath: '/admin/config/'
      preLoaderRoute: typeof AdminConfigIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/exams/': {
      id: '/_app/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof AppExamsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/jobs/active': {
      id: '/api/jobs/active'
      path: '/api/jobs/active'
      fullPath: '/api/jobs/active'
      preLoaderRoute: typeof ApiJobsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/jobs/$jobId/': {
      id: '/_app/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof AppJobsJobIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/exams/new/': {
      id: '/_app/exams/new/'
      path: '/exams/new'
      fullPath: '/exams/new/'
      preLoaderRoute: typeof AppExamsNewIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/exams/$examId/': {
      id: '/_app/exams/$examId/'
      path: '/exams/$examId'
      fullPath: '/exams/$examId/'
      preLoaderRoute: typeof AppExamsExamIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/jobs/$id/upload': {
      id: '/api/jobs/$id/upload'
      path: '/api/jobs/$id/upload'
      fullPath: '/api/jobs/$id/upload'
      preLoaderRoute: typeof ApiJobsIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id/stream': {
      id: '/api/jobs/$id/stream'
      path: '/api/jobs/$id/stream'
      fullPath: '/api/jobs/$id/stream'
      preLoaderRoute: typeof ApiJobsIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id/events': {
      id: '/api/jobs/$id/events'
      path: '/api/jobs/$id/events'
      fullPath: '/api/jobs/$id/events'
      preLoaderRoute: typeof ApiJobsIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id/cancel': {
      id: '/api/jobs/$id/cancel'
      path: '/api/jobs/$id/cancel'
      fullPath: '/api/jobs/$id/cancel'
      preLoaderRoute: typeof ApiJobsIdCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/exams/$examId/quiz/': {
      id: '/_app/exams/$examId/quiz/'
      path: '/exams/$examId/quiz'
      fullPath: '/exams/$examId/quiz/'
      preLoaderRoute: typeof AppExamsExamIdQuizIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/admin/models/$id/test-stream': {
      id: '/api/admin/models/$id/test-stream'
      path: '/api/admin/models/$id/test-stream'
      fullPath: '/api/admin/models/$id/test-stream'
      preLoaderRoute: typeof ApiAdminModelsIdTestStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/exams/$examId/quiz/$attemptId/': {
      id: '/_app/exams/$examId/quiz/$attemptId/'
      path: '/exams/$examId/quiz/$attemptId'
      fullPath: '/exams/$examId/quiz/$attemptId/'
      preLoaderRoute: typeof AppExamsExamIdQuizAttemptIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/exams/$examId/quiz/$attemptId/result': {
      id: '/_app/exams/$examId/quiz/$attemptId/result'
      path: '/exams/$examId/quiz/$attemptId/result'
      fullPath: '/exams/$examId/quiz/$attemptId/result'
      preLoaderRoute: typeof AppExamsExamIdQuizAttemptIdResultRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppExamsIndexRoute: typeof AppExamsIndexRoute
  AppExamsExamIdIndexRoute: typeof AppExamsExamIdIndexRoute
  AppExamsNewIndexRoute: typeof AppExamsNewIndexRoute
  AppJobsJobIdIndexRoute: typeof AppJobsJobIdIndexRoute
  AppExamsExamIdQuizIndexRoute: typeof AppExamsExamIdQuizIndexRoute
  AppExamsExamIdQuizAttemptIdResultRoute: typeof AppExamsExamIdQuizAttemptIdResultRoute
  AppExamsExamIdQuizAttemptIdIndexRoute: typeof AppExamsExamIdQuizAttemptIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppExamsIndexRoute: AppExamsIndexRoute,
  AppExamsExamIdIndexRoute: AppExamsExamIdIndexRoute,
  AppExamsNewIndexRoute: AppExamsNewIndexRoute,
  AppJobsJobIdIndexRoute: AppJobsJobIdIndexRoute,
  AppExamsExamIdQuizIndexRoute: AppExamsExamIdQuizIndexRoute,
  AppExamsExamIdQuizAttemptIdResultRoute:
    AppExamsExamIdQuizAttemptIdResultRoute,
  AppExamsExamIdQuizAttemptIdIndexRoute: AppExamsExamIdQuizAttemptIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConfigIndexRoute: typeof AdminConfigIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminLlmLogsIndexRoute: typeof AdminLlmLogsIndexRoute
  AdminR2LogsIndexRoute: typeof AdminR2LogsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminConfigIndexRoute: AdminConfigIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminLlmLogsIndexRoute: AdminLlmLogsIndexRoute,
  AdminR2LogsIndexRoute: AdminR2LogsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiJobsActiveRoute: ApiJobsActiveRoute,
  ApiJobsIndexRoute: ApiJobsIndexRoute,
  ApiJobsIdCancelRoute: ApiJobsIdCancelRoute,
  ApiJobsIdEventsRoute: ApiJobsIdEventsRoute,
  ApiJobsIdStreamRoute: ApiJobsIdStreamRoute,
  ApiJobsIdUploadRoute: ApiJobsIdUploadRoute,
  ApiAdminModelsIdTestStreamRoute: ApiAdminModelsIdTestStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
