/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamsIndexRouteImport } from './routes/exams.index'
import { Route as QuizIdRouteImport } from './routes/quiz.$id'
import { Route as ExamsStatsRouteImport } from './routes/exams.stats'
import { Route as ExamsIdRouteImport } from './routes/exams.$id'
import { Route as ApiTestConnectionRouteImport } from './routes/api/test-connection'
import { Route as ExamsUploadIndexRouteImport } from './routes/exams.upload/index'
import { Route as ExamsExplanationsIndexRouteImport } from './routes/exams.explanations/index'
import { Route as ApiIngestIndexRouteImport } from './routes/api/ingest/index'
import { Route as ApiChatIndexRouteImport } from './routes/api/chat/index'

const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamsRoute,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsStatsRoute = ExamsStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ExamsRoute,
} as any)
const ExamsIdRoute = ExamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExamsRoute,
} as any)
const ApiTestConnectionRoute = ApiTestConnectionRouteImport.update({
  id: '/api/test-connection',
  path: '/api/test-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsUploadIndexRoute = ExamsUploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => ExamsRoute,
} as any)
const ExamsExplanationsIndexRoute = ExamsExplanationsIndexRouteImport.update({
  id: '/explanations/',
  path: '/explanations/',
  getParentRoute: () => ExamsRoute,
} as any)
const ApiIngestIndexRoute = ApiIngestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiIngestRoute,
} as any)
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/config': typeof ConfigRoute
  '/exams': typeof ExamsRouteWithChildren
  '/memory': typeof MemoryRoute
  '/api/test-connection': typeof ApiTestConnectionRoute
  '/exams/$id': typeof ExamsIdRoute
  '/exams/stats': typeof ExamsStatsRoute
  '/quiz/$id': typeof QuizIdRoute
  '/exams/': typeof ExamsIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/api/ingest/': typeof ApiIngestIndexRoute
  '/exams/explanations/': typeof ExamsExplanationsIndexRoute
  '/exams/upload/': typeof ExamsUploadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/config': typeof ConfigRoute
  '/memory': typeof MemoryRoute
  '/api/test-connection': typeof ApiTestConnectionRoute
  '/exams/$id': typeof ExamsIdRoute
  '/exams/stats': typeof ExamsStatsRoute
  '/quiz/$id': typeof QuizIdRoute
  '/exams': typeof ExamsIndexRoute
  '/api/chat': typeof ApiChatIndexRoute
  '/api/ingest': typeof ApiIngestIndexRoute
  '/exams/explanations': typeof ExamsExplanationsIndexRoute
  '/exams/upload': typeof ExamsUploadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/config': typeof ConfigRoute
  '/exams': typeof ExamsRouteWithChildren
  '/memory': typeof MemoryRoute
  '/api/test-connection': typeof ApiTestConnectionRoute
  '/exams/$id': typeof ExamsIdRoute
  '/exams/stats': typeof ExamsStatsRoute
  '/quiz/$id': typeof QuizIdRoute
  '/exams/': typeof ExamsIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/api/ingest/': typeof ApiIngestIndexRoute
  '/exams/explanations/': typeof ExamsExplanationsIndexRoute
  '/exams/upload/': typeof ExamsUploadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chat'
    | '/config'
    | '/exams'
    | '/memory'
    | '/api/test-connection'
    | '/exams/$id'
    | '/exams/stats'
    | '/quiz/$id'
    | '/exams/'
    | '/api/chat/'
    | '/api/ingest/'
    | '/exams/explanations/'
    | '/exams/upload/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat'
    | '/config'
    | '/memory'
    | '/api/test-connection'
    | '/exams/$id'
    | '/exams/stats'
    | '/quiz/$id'
    | '/exams'
    | '/api/chat'
    | '/api/ingest'
    | '/exams/explanations'
    | '/exams/upload'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat'
    | '/config'
    | '/exams'
    | '/memory'
    | '/api/test-connection'
    | '/exams/$id'
    | '/exams/stats'
    | '/quiz/$id'
    | '/exams/'
    | '/api/chat/'
    | '/api/ingest/'
    | '/exams/explanations/'
    | '/exams/upload/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  ConfigRoute: typeof ConfigRoute
  ExamsRoute: typeof ExamsRouteWithChildren
  MemoryRoute: typeof MemoryRoute
  ApiTestConnectionRoute: typeof ApiTestConnectionRoute
  QuizIdRoute: typeof QuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/stats': {
      id: '/exams/stats'
      path: '/stats'
      fullPath: '/exams/stats'
      preLoaderRoute: typeof ExamsStatsRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/exams/$id': {
      id: '/exams/$id'
      path: '/$id'
      fullPath: '/exams/$id'
      preLoaderRoute: typeof ExamsIdRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/api/test-connection': {
      id: '/api/test-connection'
      path: '/api/test-connection'
      fullPath: '/api/test-connection'
      preLoaderRoute: typeof ApiTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/upload/': {
      id: '/exams/upload/'
      path: '/upload'
      fullPath: '/exams/upload/'
      preLoaderRoute: typeof ExamsUploadIndexRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/exams/explanations/': {
      id: '/exams/explanations/'
      path: '/explanations'
      fullPath: '/exams/explanations/'
      preLoaderRoute: typeof ExamsExplanationsIndexRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/api/ingest/': {
      id: '/api/ingest/'
      path: '/'
      fullPath: '/api/ingest/'
      preLoaderRoute: typeof ApiIngestIndexRouteImport
      parentRoute: typeof ApiIngestRoute
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/'
      fullPath: '/api/chat/'
      preLoaderRoute: typeof ApiChatIndexRouteImport
      parentRoute: typeof ApiChatRoute
    }
  }
}

interface ExamsRouteChildren {
  ExamsIdRoute: typeof ExamsIdRoute
  ExamsStatsRoute: typeof ExamsStatsRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  ExamsExplanationsIndexRoute: typeof ExamsExplanationsIndexRoute
  ExamsUploadIndexRoute: typeof ExamsUploadIndexRoute
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsIdRoute: ExamsIdRoute,
  ExamsStatsRoute: ExamsStatsRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  ExamsExplanationsIndexRoute: ExamsExplanationsIndexRoute,
  ExamsUploadIndexRoute: ExamsUploadIndexRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  ConfigRoute: ConfigRoute,
  ExamsRoute: ExamsRouteWithChildren,
  MemoryRoute: MemoryRoute,
  ApiTestConnectionRoute: ApiTestConnectionRoute,
  QuizIdRoute: QuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
