/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamsIndexRouteImport } from './routes/exams.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as QuizIdRouteImport } from './routes/quiz.$id'
import { Route as ExamsStatsRouteImport } from './routes/exams.stats'
import { Route as ExamsIdRouteImport } from './routes/exams.$id'
import { Route as ApiTestModelBenchmarkRouteImport } from './routes/api/test-model-benchmark'
import { Route as ApiTestConnectionRouteImport } from './routes/api/test-connection'
import { Route as AdminProcessLogsRouteImport } from './routes/admin.process-logs'
import { Route as AdminLlmLogsRouteImport } from './routes/admin.llm-logs'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as ExamsUploadIndexRouteImport } from './routes/exams.upload/index'
import { Route as ExamsExplanationsIndexRouteImport } from './routes/exams.explanations/index'
import { Route as ApiIngestIndexRouteImport } from './routes/api/ingest/index'
import { Route as ApiImproveQuestionsIndexRouteImport } from './routes/api/improve-questions/index'
import { Route as ApiChatIndexRouteImport } from './routes/api/chat/index'

const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsStatsRoute = ExamsStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ExamsRoute,
} as any)
const ExamsIdRoute = ExamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExamsRoute,
} as any)
const ApiTestModelBenchmarkRoute = ApiTestModelBenchmarkRouteImport.update({
  id: '/api/test-model-benchmark',
  path: '/api/test-model-benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestConnectionRoute = ApiTestConnectionRouteImport.update({
  id: '/api/test-connection',
  path: '/api/test-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProcessLogsRoute = AdminProcessLogsRouteImport.update({
  id: '/process-logs',
  path: '/process-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLlmLogsRoute = AdminLlmLogsRouteImport.update({
  id: '/llm-logs',
  path: '/llm-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const ExamsUploadIndexRoute = ExamsUploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => ExamsRoute,
} as any)
const ExamsExplanationsIndexRoute = ExamsExplanationsIndexRouteImport.update({
  id: '/explanations/',
  path: '/explanations/',
  getParentRoute: () => ExamsRoute,
} as any)
const ApiIngestIndexRoute = ApiIngestIndexRouteImport.update({
  id: '/api/ingest/',
  path: '/api/ingest/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImproveQuestionsIndexRoute =
  ApiImproveQuestionsIndexRouteImport.update({
    id: '/api/improve-questions/',
    path: '/api/improve-questions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/config': typeof ConfigRoute
  '/exams': typeof ExamsRouteWithChildren
  '/memory': typeof MemoryRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/llm-logs': typeof AdminLlmLogsRoute
  '/admin/process-logs': typeof AdminProcessLogsRoute
  '/api/test-connection': typeof ApiTestConnectionRoute
  '/api/test-model-benchmark': typeof ApiTestModelBenchmarkRoute
  '/exams/$id': typeof ExamsIdRoute
  '/exams/stats': typeof ExamsStatsRoute
  '/quiz/$id': typeof QuizIdRoute
  '/admin/': typeof AdminIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/api/improve-questions/': typeof ApiImproveQuestionsIndexRoute
  '/api/ingest/': typeof ApiIngestIndexRoute
  '/exams/explanations/': typeof ExamsExplanationsIndexRoute
  '/exams/upload/': typeof ExamsUploadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/config': typeof ConfigRoute
  '/memory': typeof MemoryRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/llm-logs': typeof AdminLlmLogsRoute
  '/admin/process-logs': typeof AdminProcessLogsRoute
  '/api/test-connection': typeof ApiTestConnectionRoute
  '/api/test-model-benchmark': typeof ApiTestModelBenchmarkRoute
  '/exams/$id': typeof ExamsIdRoute
  '/exams/stats': typeof ExamsStatsRoute
  '/quiz/$id': typeof QuizIdRoute
  '/admin': typeof AdminIndexRoute
  '/exams': typeof ExamsIndexRoute
  '/api/chat': typeof ApiChatIndexRoute
  '/api/improve-questions': typeof ApiImproveQuestionsIndexRoute
  '/api/ingest': typeof ApiIngestIndexRoute
  '/exams/explanations': typeof ExamsExplanationsIndexRoute
  '/exams/upload': typeof ExamsUploadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/config': typeof ConfigRoute
  '/exams': typeof ExamsRouteWithChildren
  '/memory': typeof MemoryRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/llm-logs': typeof AdminLlmLogsRoute
  '/admin/process-logs': typeof AdminProcessLogsRoute
  '/api/test-connection': typeof ApiTestConnectionRoute
  '/api/test-model-benchmark': typeof ApiTestModelBenchmarkRoute
  '/exams/$id': typeof ExamsIdRoute
  '/exams/stats': typeof ExamsStatsRoute
  '/quiz/$id': typeof QuizIdRoute
  '/admin/': typeof AdminIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/api/improve-questions/': typeof ApiImproveQuestionsIndexRoute
  '/api/ingest/': typeof ApiIngestIndexRoute
  '/exams/explanations/': typeof ExamsExplanationsIndexRoute
  '/exams/upload/': typeof ExamsUploadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/config'
    | '/exams'
    | '/memory'
    | '/admin/config'
    | '/admin/llm-logs'
    | '/admin/process-logs'
    | '/api/test-connection'
    | '/api/test-model-benchmark'
    | '/exams/$id'
    | '/exams/stats'
    | '/quiz/$id'
    | '/admin/'
    | '/exams/'
    | '/api/chat/'
    | '/api/improve-questions/'
    | '/api/ingest/'
    | '/exams/explanations/'
    | '/exams/upload/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat'
    | '/config'
    | '/memory'
    | '/admin/config'
    | '/admin/llm-logs'
    | '/admin/process-logs'
    | '/api/test-connection'
    | '/api/test-model-benchmark'
    | '/exams/$id'
    | '/exams/stats'
    | '/quiz/$id'
    | '/admin'
    | '/exams'
    | '/api/chat'
    | '/api/improve-questions'
    | '/api/ingest'
    | '/exams/explanations'
    | '/exams/upload'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/config'
    | '/exams'
    | '/memory'
    | '/admin/config'
    | '/admin/llm-logs'
    | '/admin/process-logs'
    | '/api/test-connection'
    | '/api/test-model-benchmark'
    | '/exams/$id'
    | '/exams/stats'
    | '/quiz/$id'
    | '/admin/'
    | '/exams/'
    | '/api/chat/'
    | '/api/improve-questions/'
    | '/api/ingest/'
    | '/exams/explanations/'
    | '/exams/upload/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChatRoute: typeof ChatRoute
  ConfigRoute: typeof ConfigRoute
  ExamsRoute: typeof ExamsRouteWithChildren
  MemoryRoute: typeof MemoryRoute
  ApiTestConnectionRoute: typeof ApiTestConnectionRoute
  ApiTestModelBenchmarkRoute: typeof ApiTestModelBenchmarkRoute
  QuizIdRoute: typeof QuizIdRoute
  ApiChatIndexRoute: typeof ApiChatIndexRoute
  ApiImproveQuestionsIndexRoute: typeof ApiImproveQuestionsIndexRoute
  ApiIngestIndexRoute: typeof ApiIngestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/stats': {
      id: '/exams/stats'
      path: '/stats'
      fullPath: '/exams/stats'
      preLoaderRoute: typeof ExamsStatsRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/exams/$id': {
      id: '/exams/$id'
      path: '/$id'
      fullPath: '/exams/$id'
      preLoaderRoute: typeof ExamsIdRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/api/test-model-benchmark': {
      id: '/api/test-model-benchmark'
      path: '/api/test-model-benchmark'
      fullPath: '/api/test-model-benchmark'
      preLoaderRoute: typeof ApiTestModelBenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-connection': {
      id: '/api/test-connection'
      path: '/api/test-connection'
      fullPath: '/api/test-connection'
      preLoaderRoute: typeof ApiTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/process-logs': {
      id: '/admin/process-logs'
      path: '/process-logs'
      fullPath: '/admin/process-logs'
      preLoaderRoute: typeof AdminProcessLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/llm-logs': {
      id: '/admin/llm-logs'
      path: '/llm-logs'
      fullPath: '/admin/llm-logs'
      preLoaderRoute: typeof AdminLlmLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/exams/upload/': {
      id: '/exams/upload/'
      path: '/upload'
      fullPath: '/exams/upload/'
      preLoaderRoute: typeof ExamsUploadIndexRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/exams/explanations/': {
      id: '/exams/explanations/'
      path: '/explanations'
      fullPath: '/exams/explanations/'
      preLoaderRoute: typeof ExamsExplanationsIndexRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/api/ingest/': {
      id: '/api/ingest/'
      path: '/api/ingest'
      fullPath: '/api/ingest/'
      preLoaderRoute: typeof ApiIngestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/improve-questions/': {
      id: '/api/improve-questions/'
      path: '/api/improve-questions'
      fullPath: '/api/improve-questions/'
      preLoaderRoute: typeof ApiImproveQuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat/'
      preLoaderRoute: typeof ApiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminConfigRoute: typeof AdminConfigRoute
  AdminLlmLogsRoute: typeof AdminLlmLogsRoute
  AdminProcessLogsRoute: typeof AdminProcessLogsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfigRoute: AdminConfigRoute,
  AdminLlmLogsRoute: AdminLlmLogsRoute,
  AdminProcessLogsRoute: AdminProcessLogsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ExamsRouteChildren {
  ExamsIdRoute: typeof ExamsIdRoute
  ExamsStatsRoute: typeof ExamsStatsRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  ExamsExplanationsIndexRoute: typeof ExamsExplanationsIndexRoute
  ExamsUploadIndexRoute: typeof ExamsUploadIndexRoute
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsIdRoute: ExamsIdRoute,
  ExamsStatsRoute: ExamsStatsRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  ExamsExplanationsIndexRoute: ExamsExplanationsIndexRoute,
  ExamsUploadIndexRoute: ExamsUploadIndexRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ChatRoute: ChatRoute,
  ConfigRoute: ConfigRoute,
  ExamsRoute: ExamsRouteWithChildren,
  MemoryRoute: MemoryRoute,
  ApiTestConnectionRoute: ApiTestConnectionRoute,
  ApiTestModelBenchmarkRoute: ApiTestModelBenchmarkRoute,
  QuizIdRoute: QuizIdRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
  ApiImproveQuestionsIndexRoute: ApiImproveQuestionsIndexRoute,
  ApiIngestIndexRoute: ApiIngestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
